/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Generate a random salt for password hashing */
export declare function generateSalt(): string
/** Derive the private key from user credentials */
export declare function derivePrivateKey(salt: string, username: string, password: string): string
/** Derive the password verifier from the private key */
export declare function deriveVerifier(privateKey: string): string
/** Generate client's ephemeral key pair */
export declare function generateClientEphemeral(): ClientEphemeral
/** Client's session key and proof */
export interface ClientSession {
  key: string
  proof: string
}
/** Derive the session key and proof on the client side */
export declare function deriveClientSession(clientSecretEphemeral: string, serverPublicEphemeral: string, salt: string, username: string, privateKey: string, clientPublicEphemeral?: string | undefined | null): ClientSession
/** Verify the server's session proof */
export declare function verifySession(clientPublicEphemeral: string, clientSession: ClientSession, serverSessionProof: string): void
/** Generate server's ephemeral key pair */
export declare function generateServerEphemeral(verifier: string): ServerEphemeral
/** Derive the session key and proof on the server side */
export declare function deriveServerSession(serverSecretEphemeral: string, clientPublicEphemeral: string, salt: string, username: string, verifier: string, clientSessionProof: string): ServerSession
/** Client's ephemeral key pair */
export declare class ClientEphemeral {
  secret: string
  public: string
}
/** Server's ephemeral key pair */
export declare class ServerEphemeral {
  secret: string
  public: string
}
/** Server's session key and proof */
export declare class ServerSession {
  key: string
  proof: string
}
export type ClientModule = Client
/** Client-side SRP implementation */
export declare class Client {
  constructor()
  generateSalt(): string
  derivePrivateKey(salt: string, username: string, password: string): string
  deriveVerifier(privateKey: string): string
  generateEphemeral(): ClientEphemeral
  deriveSession(clientSecretEphemeral: string, serverPublicEphemeral: string, salt: string, username: string, privateKey: string, clientPublicEphemeral?: string | undefined | null): ClientSession
  verifySession(clientPublicEphemeral: string, clientSession: ClientSession, serverSessionProof: string): void
}
export type ServerModule = Server
/** Server-side SRP implementation */
export declare class Server {
  constructor()
  generateEphemeral(verifier: string): ServerEphemeral
  deriveSession(serverSecretEphemeral: string, clientPublicEphemeral: string, salt: string, username: string, verifier: string, clientSessionProof: string): ServerSession
}
